# Generated by Django 5.1.6 on 2025-03-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealerNumber', models.CharField(max_length=20)),
                ('dealerName', models.CharField(max_length=200)),
                ('dealerAddress', models.CharField(max_length=200)),
                ('dealerState', models.CharField(max_length=2)),
                ('dealerZip', models.CharField(max_length=10)),
                ('dealerPhone', models.CharField(max_length=12)),
            ],
        ),
    ]
