# Generated by Django 5.1.6 on 2025-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='dealerStatus',
            field=models.CharField(default='P', max_length=2),
        ),
    ]
