# Generated by Django 5.1.6 on 2025-03-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_dealers_dealerstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='dealerStatus',
            field=models.CharField(default='NS', max_length=2),
        ),
    ]
