# Generated by Django 5.1.6 on 2025-03-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_alter_dealers_dealerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='tpaCode',
            field=models.CharField(default='NNNNN', max_length=5),
        ),
    ]
