# Generated by Django 5.1.6 on 2025-03-05 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_dealers_tpacode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='dealers',
            name='dealerCity',
            field=models.CharField(default='Need City', max_length=50),
        ),
        migrations.AddField(
            model_name='dealers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
