# Generated by Django 5.1.6 on 2025-03-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_dealers_created_at_dealers_dealercity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dealers',
            name='updated_at',
        ),
    ]
