# Generated by Django 5.1.6 on 2025-03-06 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_remove_dealers_created_at_remove_dealers_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dealers',
            new_name='Dealer',
        ),
    ]
